### PR TITLE
fix comments and remove garbage console logging

### PR DESCRIPTION
**Pull request by mtuckergd**
removing a lot of noise that is not necessary in the core files that we use
this has ***no functional changes***

### CODE REVIEW

**Comment by mjaniszewski** [comment]
:+1: Less junk == more betterer.  Merging.

**Comment by IrvinFan** [comment]
Methods `environmentify` and `multi_tenantify` are also removed from this PR. Was that intentional?

**Comment by mtuckergd** [comment]
@IrvinFan those are commented blocks. Note the `=begin` and `=end` surrounding them

**Comment by IrvinFan** [comment]
How come I missed that. :-)

**Pull request merged**
